// Auto-generated from The Bible Proves Orthodox Christianity.md — do not hand-edit.
// Regenerate with build_tsx_data.py after changing the source document.

export interface ReadingBlock {
  type: 'p' | 'quote'
  text: string
  citation?: string
}

export interface ReadingMovement {
  numeral: string
  title: string
  blocks: ReadingBlock[]
}

export const readingTitle = `The Bible Proves Orthodox Christianity`
export const readingSubtitle = `A narrative told almost entirely in the words of Christ and His Apostles, from the King James Version`
export const readingIntroNote = `A note before you read: nothing here is paraphrase. Every line set off is quoted directly from Scripture, cited as it is given. The connecting words between quotations are only there to carry you from one to the next; the argument itself is made by Christ, by Paul, by Peter, by James, by John, in their own words. Read it the way you would read Hebrews 13: as one voice, speaking to you, through many mouths.`
export const readingClosingNote = `End of this telling. Part One is quoted entirely from the King James Version. Part Two, beginning at Movement XVIII, draws instead on the recorded history of the Church herself, since the question it answers, which communion kept the pattern Scripture already required, is one history has to settle.`

export const readingMovements: ReadingMovement[] = [
  {
    numeral: 'I',
    title: `Christ Founds One Church, Not Many`,
    blocks: [
      { type: 'p', text: `Before His arrest, Jesus prayed for those who would believe on Him through the word of His apostles, and He prayed for a specific, singular thing:` },
      { type: 'quote', text: `Neither pray I for these alone, but for them also which shall believe on me through their word; That they all may be one; as thou, Father, art in me, and I in thee, that they also may be one in us: that the world may believe that thou hast sent me. And the glory which thou gavest me I have given them; that they may be one, even as we are one: I in them, and thou in me, that they may be made perfect in one; and that the world may know that thou hast sent me, and hast loved them, as thou hast loved me.`, citation: `John 17:20–23` },
      { type: 'p', text: `Not many bodies believing many things and calling it unity in spirit, but one thing, so united that the world could see it and know it. Jesus did not say He would build churches. He said:` },
      { type: 'quote', text: `And I say also unto thee, That thou art Peter, and upon this rock I will build my church; and the gates of hell shall not prevail against it.`, citation: `Matthew 16:18` },
      { type: 'p', text: `Paul, writing to Ephesus, does not leave “one” as poetry. He makes it an arithmetic:` },
      { type: 'quote', text: `Endeavouring to keep the unity of the Spirit in the bond of peace. There is one body, and one Spirit, even as ye are called in one hope of your calling; One Lord, one faith, one baptism, One God and Father of all, who is above all, and through all, and in you all.`, citation: `Ephesians 4:3–6` },
      { type: 'p', text: `One body, one faith, one baptism, not one body with many contradicting faiths sheltering under the same name. Paul says the same thing again to Corinth, in the language of a human body, where division is not a difference of opinion but a sickness:` },
      { type: 'quote', text: `For as the body is one, and hath many members, and all the members of that one body, being many, are one body: so also is Christ.… For the body is not one member, but many.… That there should be no schism in the body; but that the members should have the same care one for another.`, citation: `1 Corinthians 12:12,14,25` },
      { type: 'p', text: `A body with two heads, or ten thousand heads, each insisting it alone understands the will of the one Spirit that supposedly animates it all: that is not what Paul describes. He describes one body. The rest of this is an account, entirely in Scripture’s own words, of how that one body was given its shape, its officers, its continuation after the apostles died, and its authority to bind, to teach, and to be obeyed.` },
    ],
  },
  {
    numeral: 'II',
    title: `Christ Gives His Own Authority to the Apostles`,
    blocks: [
      { type: 'p', text: `Jesus does not leave His authority behind Him as a book to be argued over by every reader according to his own light. He hands it to men, in person, with words that transfer what is His to them:` },
      { type: 'quote', text: `And if he shall neglect to hear them, tell it unto the church: but if he neglect to hear the church, let him be unto thee as an heathen man and a publican. Verily I say unto you, Whatsoever ye shall bind on earth shall be bound in heaven: and whatsoever ye shall loose on earth shall be loosed in heaven.`, citation: `Matthew 18:17–18` },
      { type: 'p', text: `To Peter specifically, He had already said:` },
      { type: 'quote', text: `And I will give unto thee the keys of the kingdom of heaven: and whatsoever thou shalt bind on earth shall be bound in heaven: and whatsoever thou shalt loose on earth shall be loosed in heaven.`, citation: `Matthew 16:19` },
      { type: 'p', text: `After the resurrection, He makes the transfer explicit: His own mission, handed on, with His own Spirit and His own authority to forgive or to retain sin:` },
      { type: 'quote', text: `Then said Jesus to them again, Peace be unto you: as my Father hath sent me, even so send I you. And when he had said this, he breathed on them, and saith unto them, Receive ye the Holy Ghost: Whose soever sins ye remit, they are remitted unto them; and whose soever sins ye retain, they are retained.`, citation: `John 20:21–23` },
      { type: 'p', text: `And so that no one could imagine this authority was merely advisory, He said of the men He sent:` },
      { type: 'quote', text: `He that heareth you heareth me; and he that despiseth you despiseth me; and he that despiseth me despiseth him that sent me.`, citation: `Luke 10:16` },
      { type: 'p', text: `To hear the apostles is to hear Christ. To despise them is to despise Christ. This is not a claim the Church invented about herself later. It is Christ’s own claim about the men He sent, in red letters, in the Gospels a Protestant already trusts completely.` },
    ],
  },
  {
    numeral: 'III',
    title: `The Apostles Ordain Successors: Apostolic Succession in Plain Text`,
    blocks: [
      { type: 'p', text: `Here is where many are told, wrongly, that “there’s nothing about that in the Bible.” But watch what happens after Judas falls. The eleven do not treat the apostolic office as something that dies with the man. They treat it as an office, a “bishoprick,” that must be filled:` },
      { type: 'quote', text: `For it is written in the book of Psalms, Let his habitation be desolate, and let no man dwell therein: and his bishoprick let another take.`, citation: `Acts 1:20` },
      { type: 'quote', text: `And they prayed, and said, Thou, Lord, which knowest the hearts of all men, shew whether of these two thou hast chosen, That he may take part of this ministry and apostleship, from which Judas by transgression fell, that he might go to his own place. And they gave forth their lots; and the lot fell upon Matthias; and he was numbered with the eleven apostles.`, citation: `Acts 1:24–26` },
      { type: 'p', text: `That word, *bishoprick*, the King James rendering of the Greek *episkopē*, the overseer’s office, is not a later invention. It is in your own English Bible, in Acts chapter 1, applied to a successor filling a vacated apostolic office. This is the pattern the apostles then repeat everywhere they plant a church. They do not leave congregations to select their own teachers however they see fit; they *ordain* men into office, by name, with the laying on of hands, sometimes marked out for the work by fasting as well:` },
      { type: 'quote', text: `As they ministered to the Lord, and fasted, the Holy Ghost said, Separate me Barnabas and Saul for the work whereunto I have called them. And when they had fasted and prayed, and laid their hands on them, they sent them away.`, citation: `Acts 13:2–3` },
      { type: 'quote', text: `And when they had ordained them elders in every church, and had prayed with fasting, they commended them to the Lord, on whom they believed.`, citation: `Acts 14:23` },
      { type: 'quote', text: `For this cause left I thee in Crete, that thou shouldest set in order the things that are wanting, and ordain elders in every city, as I had appointed thee.`, citation: `Titus 1:5` },
      { type: 'p', text: `Paul, leaving the elders of Ephesus for the last time, tells them plainly where their authority came from: not from a congregation’s vote, but from the Holy Ghost, through ordination, for the specific purpose of overseeing Christ’s own purchased flock:` },
      { type: 'quote', text: `Take heed therefore unto yourselves, and to all the flock, over the which the Holy Ghost hath made you overseers, to feed the church of God, which he hath purchased with his own blood.`, citation: `Acts 20:28` },
      { type: 'p', text: `To Timothy, a man he himself ordained, Paul is explicit that the office and its grace are conferred by a physical, apostolic act: the laying on of hands:` },
      { type: 'quote', text: `Neglect not the gift that is in thee, which was given thee by prophecy, with the laying on of the hands of the presbytery.`, citation: `1 Timothy 4:14` },
      { type: 'quote', text: `Wherefore I put thee in remembrance that thou stir up the gift of God, which is in thee by the putting on of my hands.`, citation: `2 Timothy 1:6` },
      { type: 'p', text: `And then comes the verse that states apostolic succession outright, in so many words: not Peter to Peter’s successor only, but the whole pattern of the Church, generation after generation, an unbroken chain of ordained men handing on to ordained men what they themselves received:` },
      { type: 'quote', text: `And the things that thou hast heard of me among many witnesses, the same commit thou to faithful men, who shall be able to teach others also.`, citation: `2 Timothy 2:2` },
      { type: 'p', text: `Paul to Timothy. Timothy to faithful men. Those faithful men to others also. Four generations named in a single verse, and the pattern does not stop there. It cannot, without disobeying the verse itself.` },
      { type: 'p', text: `This office, moreover, is not one undifferentiated role. Scripture names distinct offices within it, bishops and deacons among them, each with its own qualifications spelled out for the church to recognize:` },
      { type: 'quote', text: `This is a true saying, If a man desire the office of a bishop, he desireth a good work. A bishop then must be blameless, the husband of one wife, vigilant, sober, of good behaviour, given to hospitality, apt to teach.`, citation: `1 Timothy 3:1–2` },
      { type: 'quote', text: `Likewise must the deacons be grave, not doubletongued, not given to much wine, not greedy of filthy lucre.`, citation: `1 Timothy 3:8` },
      { type: 'p', text: `Paul addresses an entire congregation this way, by its offices, as a matter of course:` },
      { type: 'quote', text: `Paul and Timotheus, the servants of Jesus Christ, to all the saints in Christ Jesus which are at Philippi, with the bishops and deacons.`, citation: `Philippians 1:1` },
      { type: 'p', text: `Bishops, elders, and deacons, named as such, with qualifications for each, are not a later medieval invention layered onto a flat congregation of equals. They are in the text.` },
    ],
  },
  {
    numeral: 'IV',
    title: `Obey and Submit to Your Leaders`,
    blocks: [
      { type: 'p', text: `Having established that there are ordained men holding real, transmitted, apostolic office, Scripture now tells you, directly, how you are to relate to them. Not as one opinion among many you are free to weigh against your own:` },
      { type: 'quote', text: `Remember them which have the rule over you, who have spoken unto you the word of God: whose faith follow, considering the end of their conversation.`, citation: `Hebrews 13:7` },
      { type: 'quote', text: `Obey them that have the rule over you, and submit yourselves: for they watch for your souls, as they that must give account, that they may do it with joy, and not with grief: for that is unprofitable for you.`, citation: `Hebrews 13:17` },
      { type: 'p', text: `Paul tells the Thessalonians the same thing: to *know*, to *esteem*, those set over them, precisely because they are set “over you in the Lord”:` },
      { type: 'quote', text: `And we beseech you, brethren, to know them which labour among you, and are over you in the Lord, and admonish you; And to esteem them very highly in love for their work’s sake. And be at peace among yourselves.`, citation: `1 Thessalonians 5:12–13` },
      { type: 'p', text: `He tells Timothy the elders who rule well are worthy of *double honour*, not suspicion, not a standing invitation to be second-guessed by every reader with a concordance:` },
      { type: 'quote', text: `Let the elders that rule well be counted worthy of double honour, especially they who labour in the word and doctrine.`, citation: `1 Timothy 5:17` },
      { type: 'p', text: `And Peter, an elder himself, writing to elders and to those under them, makes the shape of the whole Church visible in a single passage: shepherds who oversee, and a flock that submits, all of it clothed in humility toward one another, not each man ruling himself:` },
      { type: 'quote', text: `The elders which are among you I exhort, who am also an elder, and a witness of the sufferings of Christ, and also a partaker of the glory that shall be revealed: Feed the flock of God which is among you, taking the oversight thereof, not by constraint, but willingly; not for filthy lucre, but of a ready mind; Neither as being lords over God’s heritage, but being ensamples to the flock.… Likewise, ye younger, submit yourselves unto the elder. Yea, all of you be subject one to another, and be clothed with humility: for God resisteth the proud, and giveth grace to the humble.`, citation: `1 Peter 5:1–5` },
    ],
  },
  {
    numeral: 'V',
    title: `Confession and the Authority to Absolve`,
    blocks: [
      { type: 'p', text: `This is not left as a theory of authority with no visible practice attached to it. The very power Christ gave His apostles to remit and retain sin, and to bind and loose, is shown in Scripture being exercised, in the ordinary life of a congregation, by its elders, not privately worked out between a man and God alone with no one else involved:` },
      { type: 'quote', text: `Is any sick among you? let him call for the elders of the church; and let them pray over him, anointing him with oil in the name of the Lord: And the prayer of faith shall save the sick, and the Lord shall raise him up; and if he have committed sins, they shall be forgiven him. Confess your faults one to another, and pray one for another, that ye may be healed. The effectual fervent prayer of a righteous man availeth much.`, citation: `James 5:14–16` },
      { type: 'p', text: `Notice the shape of it: a man does not simply settle his sin in silence. He *calls for the elders*. He *confesses*. They *pray*. And forgiveness follows. This is the same authority already given in Movement II, that whosesoever sins the apostles remit are remitted, and whatsoever they bind or loose on earth is bound or loosed in heaven, now shown functioning exactly where you would expect it to function: among the elders of the church, not apart from them.` },
    ],
  },
  {
    numeral: 'VI',
    title: `No Private Interpretation: Scripture Entrusted to the Church`,
    blocks: [
      { type: 'p', text: `This is the point where a Protestant reader must reckon with a verse he already owns but rarely applies to himself. Peter does not say Scripture is easy and self-evident to whoever picks it up. He says the opposite:` },
      { type: 'quote', text: `Knowing this first, that no prophecy of the scripture is of any private interpretation. For the prophecy came not in old time by the will of man: but holy men of God spake as they were moved by the Holy Ghost.`, citation: `2 Peter 1:20–21` },
      { type: 'p', text: `And Peter says this in the very same letter where he discusses Paul’s epistles by name, warning that even they are hard, and that mishandling them without guidance leads not to enlightenment, but to destruction:` },
      { type: 'quote', text: `And account that the longsuffering of our Lord is salvation; even as our beloved brother Paul also according to the wisdom given unto him hath written unto you; As also in all his epistles, speaking in them of these things; in which are some things hard to be understood, which they that are unlearned and unstable wrest, as they do also the other scriptures, unto their own destruction.`, citation: `2 Peter 3:15–16` },
      { type: 'p', text: `If the *unlearned and unstable*, a description that fits any of us, alone, without a teacher, will wrest Scripture “unto their own destruction,” then Scripture itself tells you that you need something more than yourself and a printed page. Paul tells Timothy plainly what that something is:` },
      { type: 'quote', text: `But if I tarry long, that thou mayest know how thou oughtest to behave thyself in the house of God, which is the church of the living God, the pillar and ground of the truth.`, citation: `1 Timothy 3:15` },
      { type: 'p', text: `Not the book alone: the *church* is called the pillar and ground of the truth. And that same church hands down not only the written word but a spoken and lived tradition Paul commands to be *held*:` },
      { type: 'quote', text: `Therefore, brethren, stand fast, and hold the traditions which ye have been taught, whether by word, or our epistle.`, citation: `2 Thessalonians 2:15` },
      { type: 'quote', text: `Now we command you, brethren, in the name of our Lord Jesus Christ, that ye withdraw yourselves from every brother that walketh disorderly, and not after the tradition which he received of us.`, citation: `2 Thessalonians 3:6` },
      { type: 'quote', text: `Now I praise you, brethren, that ye remember me in all things, and keep the ordinances, as I delivered them to you.`, citation: `1 Corinthians 11:2` },
      { type: 'p', text: `Whether by word, or by epistle: both. Delivered and kept, not reconstructed from scratch by every generation using the text alone.` },
    ],
  },
  {
    numeral: 'VII',
    title: `Holy Tradition: What Was Never Written Down`,
    blocks: [
      { type: 'p', text: `Scripture is not shy about admitting that it does not contain everything. John closes his own Gospel by saying so directly:` },
      { type: 'quote', text: `And there are also many other things which Jesus did, the which, if they should be written every one, I suppose that even the world itself could not contain the books that should be written. Amen.`, citation: `John 21:25` },
      { type: 'quote', text: `And many other signs truly did Jesus in the presence of his disciples, which are not written in this book.`, citation: `John 20:30` },
      { type: 'p', text: `John does not treat this gap as a loss to be regretted. In his own letters, he says plainly that he is choosing, on purpose, to leave certain things unwritten, in favor of a living, spoken word he considers no less complete and no less able to bring joy:` },
      { type: 'quote', text: `Having many things to write unto you, I would not write with paper and ink: but I trust to come unto you, and speak face to face, that our joy may be full.`, citation: `2 John 1:12` },
      { type: 'quote', text: `I had many things to write, but I will not with ink and pen write unto thee: But I trust I shall shortly see thee, and we shall speak face to face.`, citation: `3 John 1:13–14` },
      { type: 'p', text: `Paul does the same thing with the church at Corinth, reserving part of his instruction for his own presence among them rather than committing it to the letter at all:` },
      { type: 'quote', text: `And the rest will I set in order when I come.`, citation: `1 Corinthians 11:34` },
      { type: 'p', text: `This is the same pattern of transmission already shown throughout this document: the faithful men of Movement III, taught by word of mouth and entrusted to teach others also; the traditions Movement VI already showed Paul commanding to be held “whether by word, or our epistle.” Scripture describes its own transmission as partly written and partly spoken, and nowhere calls the second inferior to the first.` },
      { type: 'p', text: `Even the verse most often raised to settle the question, read in full rather than in isolation, does not say what it is used to say:` },
      { type: 'quote', text: `But continue thou in the things which thou hast learned and hast been assured of, knowing of whom thou hast learned them; And that from a child thou hast known the holy scriptures, which are able to make thee wise unto salvation through faith which is in Christ Jesus. All scripture is given by inspiration of God, and is profitable for doctrine, for reproof, for correction, for instruction in righteousness: That the man of God may be perfect, throughly furnished unto all good works.`, citation: `2 Timothy 3:14–17` },
      { type: 'p', text: `Notice what comes immediately before the famous claim about Scripture’s profitability: continue in what thou hast learned, *knowing of whom thou hast learned them*. Paul points Timothy to a person before he points him to a text. And the “holy scriptures” Timothy had known from a child, in a letter written before the New Testament existed as a collected book, were the Old Testament. This verse cannot be made to mean “the Bible alone, nothing else needed” without also declaring the very epistle Timothy is holding, and the personal instruction Paul has just appealed to, unnecessary. It cannot mean that and remain coherent.` },
    ],
  },
  {
    numeral: 'VIII',
    title: `Warnings Against Schism and “Just Me and My Bible”`,
    blocks: [
      { type: 'p', text: `Paul does not treat splitting from the visible body, or founding a new one under a new name or a new favored teacher, as a minor disagreement between equally valid Christians. He treats it as a scandal to be corrected by apostolic authority: his own:` },
      { type: 'quote', text: `Now I beseech you, brethren, by the name of our Lord Jesus Christ, that ye all speak the same thing, and that there be no divisions among you; but that ye be perfectly joined together in the same mind and in the same judgment.`, citation: `1 Corinthians 1:10` },
      { type: 'quote', text: `For it hath been declared unto me of you, my brethren, by them which are of the house of Chloe, that there are contentions among you. Now this I say, that every one of you saith, I am of Paul; and I of Apollos; and I of Cephas; and I of Christ. Is Christ divided? was Paul crucified for you? or were ye baptized in the name of Paul?`, citation: `1 Corinthians 1:11–13` },
      { type: 'p', text: `Notice: even “I am of Christ,” said by someone using it to set himself apart from the others, is listed among the *divisions* Paul is rebuking. Loyalty to Christ is not proof against schism if it is used to break fellowship with the rest of the body. Paul calls this what it is: not maturity, but its opposite:` },
      { type: 'quote', text: `And I, brethren, could not speak unto you as unto spiritual, but as unto carnal, even as unto babes in Christ.… For ye are yet carnal: for whereas there is among you envying, and strife, and divisions, are ye not carnal, and walk as men? For while one saith, I am of Paul; and another, I am of Apollos; are ye not carnal?`, citation: `1 Corinthians 3:1,3–4` },
      { type: 'p', text: `He gives the same instruction to Rome that he gave to Corinth: not to weigh each new teaching on its own merits indefinitely, but to mark and avoid those who cause division from what has already been taught:` },
      { type: 'quote', text: `Now I beseech you, brethren, mark them which cause divisions and offences contrary to the doctrine which ye have learned; and avoid them.`, citation: `Romans 16:17` },
      { type: 'p', text: `He tells Titus exactly how long to be patient with someone who persists in factional teaching after being corrected by the church’s authority:` },
      { type: 'quote', text: `A man that is an heretick after the first and second admonition reject; Knowing that he that is such is subverted, and sinneth, being condemned of himself.`, citation: `Titus 3:10–11` },
      { type: 'p', text: `And Jude, writing to the whole church, does not describe the faith as something each believer reconstructs from Scripture on his own initiative. He describes it as something already given, complete, to be defended as received:` },
      { type: 'quote', text: `Beloved, when I gave all diligence to write unto you of the common salvation, it was needful for me to write unto you, and exhort you that ye should earnestly contend for the faith which was once delivered unto the saints.`, citation: `Jude 1:3` },
      { type: 'p', text: `*Once delivered.* Not once discovered by each man for himself, in each generation, from the text alone.` },
    ],
  },
  {
    numeral: 'IX',
    title: `Baptismal Regeneration: Entering the One Body`,
    blocks: [
      { type: 'p', text: `Before a man can be fed as a member of the one body, he must first be joined to it, and Scripture does not describe that joining as a bare symbol or an outward gesture only. Christ Himself makes it a condition of entering the kingdom:` },
      { type: 'quote', text: `Jesus answered, Verily, verily, I say unto thee, Except a man be born of water and of the Spirit, he cannot enter into the kingdom of God.`, citation: `John 3:5` },
      { type: 'p', text: `On the day the Church was born, Peter does not tell the crowd to merely believe and consider themselves saved. He gives them something to do, tied directly to the forgiveness of sins and the gift of the Spirit:` },
      { type: 'quote', text: `Then Peter said unto them, Repent, and be baptized every one of you in the name of Jesus Christ for the remission of sins, and ye shall receive the gift of the Holy Ghost.`, citation: `Acts 2:38` },
      { type: 'p', text: `Paul describes baptism not as a picture painted after the fact of an invisible inward change, but as the very act by which a man is joined to Christ’s death and raised to a new life:` },
      { type: 'quote', text: `Know ye not, that so many of us as were baptized into Jesus Christ were baptized into his death? Therefore we are buried with him by baptism into death: that like as Christ was raised up from the dead by the glory of the Father, even so we also should walk in newness of life.`, citation: `Romans 6:3–4` },
      { type: 'p', text: `He tells Titus that this is how salvation itself comes, by mercy, through a washing:` },
      { type: 'quote', text: `Not by works of righteousness which we have done, but according to his mercy he saved us, by the washing of regeneration, and renewing of the Holy Ghost.`, citation: `Titus 3:5` },
      { type: 'p', text: `Peter states it as plainly as language allows, and even anticipates the objection that this is merely about the water itself, ruling it out in the same breath:` },
      { type: 'quote', text: `The like figure whereunto even baptism doth also now save us (not the putting away of the filth of the flesh, but the answer of a good conscience toward God,) by the resurrection of Jesus Christ.`, citation: `1 Peter 3:21` },
      { type: 'p', text: `And when Ananias comes to the newly converted Saul, blind and fasting in Damascus, he does not tell him his sins are already washed away by the faith he has just professed. He tells him to rise and be baptized, and *then* wash them away:` },
      { type: 'quote', text: `And now why tarriest thou? arise, and be baptized, and wash away thy sins, calling on the name of the Lord.`, citation: `Acts 22:16` },
      { type: 'p', text: `Born of water and the Spirit. For the remission of sins. Buried with Him, raised to newness of life. The washing of regeneration. Doth also now save us. Wash away thy sins. This is not one obscure verse strained past its meaning. It is the consistent language of six different writers describing the same doorway into the one body.` },
    ],
  },
  {
    numeral: 'X',
    title: `The Eucharist as the Visible Bond of the One Body`,
    blocks: [
      { type: 'p', text: `The unity Christ prayed for in John 17 is not left abstract. Christ Himself ties it to something concrete, physical, and shared: His own body and blood, really eaten and really drunk, not a symbol chosen among several acceptable interpretations:` },
      { type: 'quote', text: `Then Jesus said unto them, Verily, verily, I say unto you, Except ye eat the flesh of the Son of man, and drink his blood, ye have no life in you. Whoso eateth my flesh, and drinketh my blood, hath eternal life; and I will raise him up at the last day. For my flesh is meat indeed, and my blood is drink indeed. He that eateth my flesh, and drinketh my blood, dwelleth in me, and I in him.`, citation: `John 6:53–56` },
      { type: 'p', text: `Paul explains why this is the sacrament of unity rather than merely of personal piety: because it is *one* bread, and eating it makes many people *one* body:` },
      { type: 'quote', text: `The cup of blessing which we bless, is it not the communion of the blood of Christ? The bread which we break, is it not the communion of the body of Christ? For we being many are one bread, and one body: for we are all partakers of that one bread.`, citation: `1 Corinthians 10:16–17` },
      { type: 'p', text: `He hands down, as something he *received* and *delivered*, not invented, the words of institution themselves, and warns that this is not a meal to be approached carelessly or apart from rightly discerning what it is:` },
      { type: 'quote', text: `For I have received of the Lord that which also I delivered unto you, That the Lord Jesus the same night in which he was betrayed took bread: And when he had given thanks, he brake it, and said, Take, eat: this is my body, which is broken for you: this do in remembrance of me.… For as often as ye eat this bread, and drink this cup, ye do shew the Lord’s death till he come. Wherefore whosoever shall eat this bread, and drink this cup of the Lord, unworthily, shall be guilty of the body and blood of the Lord. But let a man examine himself, and so let him eat of that bread, and drink of that cup. For he that eateth and drinketh unworthily, eateth and drinketh damnation to himself, not discerning the Lord’s body.`, citation: `1 Corinthians 11:23–24,26–29` },
      { type: 'p', text: `And this, the breaking of bread, is placed by Luke at the very center of what the earliest church, gathered under the apostles, actually did together, alongside apostolic teaching itself:` },
      { type: 'quote', text: `And they continued stedfastly in the apostles’ doctrine and fellowship, and in breaking of bread, and in prayers.`, citation: `Acts 2:42` },
      { type: 'p', text: `Apostles’ doctrine, fellowship, the breaking of bread, and prayers: one continuous, visible, communal life, not four optional and separable practices.` },
    ],
  },
  {
    numeral: 'XI',
    title: `The Priesthood: Ministers and Stewards of the Mysteries`,
    blocks: [
      { type: 'p', text: `The Eucharist just described is not something a congregation administers to itself. Scripture describes those who preside at it in the same terms it uses of the priesthood it fulfills, men taken from among their brethren and ordained to offer on their behalf:` },
      { type: 'quote', text: `For every high priest taken from among men is ordained for men in things pertaining to God, that he may offer both gifts and sacrifices for sins.`, citation: `Hebrews 5:1` },
      { type: 'p', text: `That pattern finds its perfection in Christ, who fulfills it not by human descent but by God’s own oath, and holds it forever:` },
      { type: 'quote', text: `But this man, because he continueth ever, hath an unchangeable priesthood. Wherefore he is able also to save them to the uttermost that come unto God by him, seeing he ever liveth to make intercession for them.`, citation: `Hebrews 7:24–25` },
      { type: 'p', text: `Every priesthood exercised within the Church is a participation in His, not a rival to it. That is exactly the language Paul reaches for when he describes his own ministry, not merely as the preaching of ideas, but as a trust over sacred things belonging to someone else:` },
      { type: 'quote', text: `Let a man so account of us, as of the ministers of Christ, and stewards of the mysteries of God.`, citation: `1 Corinthians 4:1` },
      { type: 'p', text: `Peter tells the whole Church, every believer, that they are a royal priesthood, and that is true, and worth holding onto exactly as it is written:` },
      { type: 'quote', text: `Ye also, as lively stones, are built up a spiritual house, an holy priesthood, to offer up spiritual sacrifices, acceptable to God by Jesus Christ.… But ye are a chosen generation, a royal priesthood, an holy nation, a peculiar people; that ye should shew forth the praises of him who hath called you out of darkness into his marvellous light.`, citation: `1 Peter 2:5,9` },
      { type: 'p', text: `But this does not erase the distinct ministry Paul just described in the same Scripture. The whole Church offers up spiritual sacrifices of praise, and the writer to the Hebrews names exactly what those are:` },
      { type: 'quote', text: `By him therefore let us offer the sacrifice of praise to God continually, that is, the fruit of our lips giving thanks to his name. But to do good and to communicate forget not: for with such sacrifices God is well pleased.`, citation: `Hebrews 13:15–16` },
      { type: 'p', text: `That is the priesthood of all believers, real and Scriptural. It stands alongside, not instead of, the ordained stewardship of the mysteries just named, in the same way the ordained elders of Movement IV stand alongside, not instead of, the whole flock they were set to oversee. And where there are stewards of the mysteries, there is something for them to steward. The writer to the Hebrews is explicit that Christians have an altar:` },
      { type: 'quote', text: `We have an altar, whereof they have no right to eat which serve the tabernacle.`, citation: `Hebrews 13:10` },
      { type: 'p', text: `Centuries before, the prophet Malachi had already foretold exactly this: a priestly offering, no longer confined to one Temple in Jerusalem, but lifted up in every place, among nations who did not yet know the God of Israel:` },
      { type: 'quote', text: `For from the rising of the sun even unto the going down of the same my name shall be great among the Gentiles; and in every place incense shall be offered unto my name, and a pure offering: for my name shall be great among the heathen, saith the LORD of hosts.`, citation: `Malachi 1:11` },
      { type: 'p', text: `An altar. A pure offering, lifted up in every place among the Gentiles, not confined to a single Temple. Stewards ordained to minister it, taken from among men, as every priesthood before Christ’s own had been. This is not a departure from what the Eucharist in Movement X already showed. It is its necessary shape: a sacrifice needs someone standing at the altar to offer it, and Scripture already told you who that would be.` },
    ],
  },
  {
    numeral: 'XII',
    title: `Fasting and the Ascetic Life`,
    blocks: [
      { type: 'p', text: `Christ does not treat fasting as an Old Covenant practice His followers may safely leave behind. He assumes it, and simply tells them how to do it rightly:` },
      { type: 'quote', text: `Moreover when ye fast, be not, as the hypocrites, of a sad countenance: for they disfigure their faces, that they may appear unto men to fast. Verily I say unto you, They have their reward. But thou, when thou fastest, anoint thine head, and wash thy face; That thou appear not unto men to fast, but unto thy Father which is in secret: and thy Father, which seeth in secret, shall reward thee openly.`, citation: `Matthew 6:16–18` },
      { type: 'p', text: `When John’s disciples ask why His own do not fast as often as others, He does not say fasting has passed away with the Old Covenant. He says the time for His followers to fast is still to come, once He has departed:` },
      { type: 'quote', text: `Then came to him the disciples of John, saying, Why do we and the Pharisees fast oft, but thy disciples fast not? And Jesus said unto them, Can the children of the bridechamber mourn, as long as the bridegroom is with them? but the days will come, when the bridegroom shall be taken from them, and then shall they fast.`, citation: `Matthew 9:14–15` },
      { type: 'p', text: `Paul, writing after that departure, names fasting repeatedly, not as a private eccentricity, but as part of the ordinary shape of apostolic life:` },
      { type: 'quote', text: `In stripes, in imprisonments, in tumults, in labours, in watchings, in fastings.`, citation: `2 Corinthians 6:5` },
      { type: 'quote', text: `In weariness and painfulness, in watchings often, in hunger and thirst, in fastings often, in cold and nakedness.`, citation: `2 Corinthians 11:27` },
      { type: 'p', text: `He tells even married believers to set aside the marriage bed for a time, by mutual consent, for this very purpose, showing the discipline was expected of ordinary lay Christians and not apostles alone:` },
      { type: 'quote', text: `Defraud ye not one the other, except it be with consent for a time, that ye may give yourselves to fasting and prayer; and come together again, that Satan tempt you not for your incontinency.`, citation: `1 Corinthians 7:5` },
      { type: 'p', text: `And Luke commends it as the mark of a life given wholly to God, in the aged prophetess who recognized the infant Christ:` },
      { type: 'quote', text: `And she was a widow of about fourscore and four years, which departed not from the temple, but served God with fastings and prayers night and day.`, citation: `Luke 2:37` },
      { type: 'p', text: `This is not peripheral to the pattern already shown in this document. Movement III already showed the apostles fasting at the very moment they ordained Barnabas and Saul, and fasting again as they ordained elders in every church. The Church’s most serious acts and its ordinary discipline are woven from the same thread.` },
      { type: 'p', text: `The one passage most often raised against this, read in full rather than in part, says something different from what it is used to say:` },
      { type: 'quote', text: `Now the Spirit speaketh expressly, that in the latter times some shall depart from the faith, giving heed to seducing spirits, and doctrines of devils; Speaking lies in hypocrisy; having their conscience seared with a hot iron; Forbidding to marry, and commanding to abstain from meats, which God hath created to be received with thanksgiving of them which believe and know the truth. For every creature of God is good, and nothing to be refused, if it be received with thanksgiving: For it is sanctified by the word of God and prayer.`, citation: `1 Timothy 4:1–5` },
      { type: 'p', text: `What is condemned here is *forbidding* marriage and food as evil in themselves, a permanent verdict against what God made good. What the passage itself commends, in the very same breath, is receiving that same food *with thanksgiving*, set apart by prayer, which is exactly what voluntary, temporary fasting has always been: not a verdict that food or marriage is unclean, but a discipline freely taken up for a season, precisely as Christ, Paul, and Luke have already described it. Paul sums up the whole practice in a single sentence about his own body:` },
      { type: 'quote', text: `But I keep under my body, and bring it into subjection: lest that by any means, when I have preached to others, I myself should be a castaway.`, citation: `1 Corinthians 9:27` },
    ],
  },
  {
    numeral: 'XIII',
    title: `The Church Is Visible, Not Invisible`,
    blocks: [
      { type: 'p', text: `Jesus describes His church with an image that cannot be reconciled with something scattered, hidden, or known only to God:` },
      { type: 'quote', text: `Ye are the light of the world. A city that is set on an hill cannot be hid.`, citation: `Matthew 5:14` },
      { type: 'p', text: `When a dispute over doctrine arose in the earliest years, not a small one, but a question touching salvation itself, the answer given in Scripture is not “everyone consult the text and decide for himself.” It is a visible council, of apostles and elders, gathered in one place, exercising real authority, and issuing a binding decision in the name of the Holy Ghost:` },
      { type: 'quote', text: `They determined that Paul and Barnabas, and certain other of them, should go up to Jerusalem unto the apostles and elders about this question.`, citation: `Acts 15:2` },
      { type: 'quote', text: `And the apostles and elders came together for to consider of this matter.`, citation: `Acts 15:6` },
      { type: 'quote', text: `For it seemed good to the Holy Ghost, and to us, to lay upon you no greater burden than these necessary things.`, citation: `Acts 15:28` },
      { type: 'p', text: `This is the model Jesus Himself had already given for settling disputes: not “search the Scriptures alone until you’re satisfied,” but ultimately, “tell it unto the church”:` },
      { type: 'quote', text: `And if he shall neglect to hear them, tell it unto the church: but if he neglect to hear the church, let him be unto thee as an heathen man and a publican.`, citation: `Matthew 18:17` },
      { type: 'p', text: `That same visibility shows up in the ordinary rhythm of worship. This was not a scattered, occasional, private devotion, but a fixed, gathered, weekly pattern that could be named and joined:` },
      { type: 'quote', text: `And upon the first day of the week, when the disciples came together to break bread, Paul preached unto them, ready to depart on the morrow, and continued his speech until midnight.`, citation: `Acts 20:7` },
      { type: 'p', text: `A church that can be told something, that can hear or fail to hear, that a man can be put outside of, that gathers on a known day for a known purpose: that is a visible, identifiable body, not an invisible aggregate of individually saved persons who happen to share private beliefs.` },
    ],
  },
  {
    numeral: 'XIV',
    title: `The Theotokos and the Communion of Saints`,
    blocks: [
      { type: 'p', text: `Scripture’s own language about Mary is stronger than the caution many Protestants are taught to bring to it. The angel Gabriel greets her, before she has done anything at all except be chosen, with a title given to no other human being in Scripture:` },
      { type: 'quote', text: `And the angel came in unto her, and said, Hail, thou that art highly favoured, the Lord is with thee: blessed art thou among women.`, citation: `Luke 1:28` },
      { type: 'p', text: `When Mary visits Elisabeth, the greeting is confirmed, and the title given her is not vague reverence but a direct name: the mother of the Lord. And this is said, the text is careful to note, under the inspiration of the Holy Ghost, not as Elisabeth’s private opinion:` },
      { type: 'quote', text: `And it came to pass, that, when Elisabeth heard the salutation of Mary, the babe leaped in her womb; and Elisabeth was filled with the Holy Ghost: And she spake out with a loud voice, and said, Blessed art thou among women, and blessed is the fruit of thy womb. And whence is this to me, that the mother of my Lord should come to me?`, citation: `Luke 1:41–43` },
      { type: 'p', text: `Mary’s own response is not to deflect the honor, but to prophesy, under the same Spirit, that it will not stop with Elisabeth:` },
      { type: 'quote', text: `And Mary said, My soul doth magnify the Lord, And my spirit hath rejoiced in God my Saviour. For he hath regarded the low estate of his handmaiden: for, behold, from henceforth all generations shall call me blessed.`, citation: `Luke 1:46–48` },
      { type: 'p', text: `*All generations.* Not a title Elisabeth alone was permitted to use, or one generation only. And at the cross, Christ Himself does not leave this relationship behind Him as merely biological. He gives her, with His own dying words, to the beloved disciple, and the disciple to her:` },
      { type: 'quote', text: `When Jesus therefore saw his mother, and the disciple standing by, whom he loved, he saith unto his mother, Woman, behold thy son! Then saith he to the disciple, Behold thy mother! And from that hour that disciple took her unto his own home.`, citation: `John 19:26–27` },
      { type: 'p', text: `None of this is worship. Nowhere does Scripture instruct Mary, or any saint, to be served or bowed down to as God alone is served, and nothing here should be read that way. It is the honor already established in Movement IV, given to elders and leaders, extended here to the one Christ Himself honored above all others. That same principle extends to the wider company of the redeemed. The writer to the Hebrews does not describe the saints who have gone before as gone, absent, unaware:` },
      { type: 'quote', text: `Wherefore seeing we also are compassed about with so great a cloud of witnesses, let us lay aside every weight, and the sin which doth so easily beset us, and let us run with patience the race that is set before us.`, citation: `Hebrews 12:1` },
      { type: 'p', text: `Christ Himself gives the reason such language is possible at all:` },
      { type: 'quote', text: `For he is not a God of the dead, but of the living: for all live unto him.`, citation: `Luke 20:38` },
      { type: 'p', text: `And John’s own vision of heaven shows exactly what that living communion looks like, in an image that is neither idolatry nor mere metaphor, but glorified elders in heaven, offering up the prayers of the saints:` },
      { type: 'quote', text: `And when he had taken the book, the four beasts and four and twenty elders fell down before the Lamb, having every one of them harps, and golden vials full of odours, which are the prayers of saints.`, citation: `Revelation 5:8` },
      { type: 'p', text: `A cloud of witnesses who are alive unto God, and elders in heaven presenting the prayers of the saints before the Lamb: this is not a doctrine invented centuries later. It is what the text already says.` },
    ],
  },
  {
    numeral: 'XV',
    title: `Icons and Images in Worship`,
    blocks: [
      { type: 'p', text: `This objection deserves to be met honestly, starting with the commandment itself, quoted in full rather than summarized:` },
      { type: 'quote', text: `Thou shalt not make unto thee any graven image, or any likeness of any thing that is in heaven above, or that is in the earth beneath, or that is in the water under the earth: Thou shalt not bow down thyself to them, nor serve them: for I the LORD thy God am a jealous God.`, citation: `Exodus 20:4–5` },
      { type: 'p', text: `Read that command, and then read what the same God, through the same Moses, commands only five chapters later, for the holiest object Israel possessed, the mercy seat of the Ark itself:` },
      { type: 'quote', text: `And thou shalt make two cherubims of gold, of beaten work shalt thou make them, in the two ends of the mercy seat. And make one cherub on the one end, and the other cherub on the other end: even of the mercy seat shall ye make the cherubims on the two ends thereof. And the cherubims shall stretch forth their wings on high, covering the mercy seat with their wings, and their faces shall look one to another; toward the mercy seat shall the faces of the cherubims be.`, citation: `Exodus 25:18–20` },
      { type: 'p', text: `Graven, carved images of heavenly beings, commanded by God, placed at the very center of Israel’s worship. The same pattern appears again when the people are dying of snakebite in the wilderness. God does not forbid an image here. He commands one, and ties looking upon it to life itself:` },
      { type: 'quote', text: `And the LORD said unto Moses, Make thee a fiery serpent, and set it upon a pole: and it shall come to pass, that every one that is bitten, when he looketh upon it, shall live. And Moses made a serpent of brass, and put it upon a pole, and it came to pass, that if a serpent had bitten any man, when he beheld the serpent of brass, he lived.`, citation: `Numbers 21:8–9` },
      { type: 'p', text: `Christ Himself later treats that very image as a valid type of His own crucifixion, not as a relic of a forbidden practice to be quietly forgotten:` },
      { type: 'quote', text: `And as Moses lifted up the serpent in the wilderness, even so must the Son of man be lifted up.`, citation: `John 3:14` },
      { type: 'p', text: `And when Solomon builds the Temple, God’s own house, it is filled, walls and inner sanctuary alike, with carved images:` },
      { type: 'quote', text: `And within the oracle he made two cherubims of olive tree, each ten cubits high.`, citation: `1 Kings 6:23` },
      { type: 'quote', text: `And he carved all the walls of the house round about with carved figures of cherubims and palm trees and open flowers, within and without.`, citation: `1 Kings 6:29` },
      { type: 'p', text: `This was not Solomon’s private artistic license. David tells us plainly where the pattern for the Temple, images included, came from:` },
      { type: 'quote', text: `All this, said David, the LORD made me understand in writing by his hand upon me, even all the works of this pattern.`, citation: `1 Chronicles 28:19` },
      { type: 'p', text: `Put the commandment and these examples side by side, and the shape of it becomes clear. What is forbidden is bowing down to an image and serving it *as God*, worshipping the creature instead of the Creator. What is commanded, repeatedly, by the same God, is the making of sacred images for use in true worship of Him: on the Ark, on the walls of His own Temple, and lifted up before a dying people so that looking upon it, they might live. The line Scripture draws is not between image and no image. It is between worship and idolatry.` },
    ],
  },
  {
    numeral: 'XVI',
    title: `Scripture Warns You, in Advance, About This Very Argument`,
    blocks: [
      { type: 'p', text: `It would be easy to think the multiplication of denominations, each claiming to follow the Bible alone, each disagreeing with the last, is simply what happens as people study earnestly. Scripture does not describe it that way. It describes it, in advance, as exactly what was foretold, and locates its source not in outsiders, but *from among the church’s own*:` },
      { type: 'quote', text: `For I know this, that after my departing shall grievous wolves enter in among you, not sparing the flock. Also of your own selves shall men arise, speaking perverse things, to draw away disciples after them.`, citation: `Acts 20:29–30` },
      { type: 'p', text: `Paul warns Timothy of a time, recognizable to anyone who has watched a congregation dismiss one teacher for another more pleasing one, when people will not seek sound doctrine, but a teacher who tells them what they already want to hear:` },
      { type: 'quote', text: `For the time will come when they will not endure sound doctrine; but after their own lusts shall they heap to themselves teachers, having itching ears; And they shall turn away their ears from the truth, and shall be turned unto fables.`, citation: `2 Timothy 4:3–4` },
      { type: 'p', text: `Peter says the same false teaching will not arrive with a label reading “heresy” on it, but will be brought in *privily*: quietly, plausibly, from within:` },
      { type: 'quote', text: `But there were false prophets also among the people, even as there shall be false teachers among you, who privily shall bring in damnable heresies, even denying the Lord that bought them, and bring upon themselves swift destruction.`, citation: `2 Peter 2:1` },
      { type: 'p', text: `And Paul places the bar for a *true* gospel not in whatever seems most compelling to an individual reader, but in continuity with what was *already* preached by the apostles, so high a bar that he applies it even to himself and to angels:` },
      { type: 'quote', text: `But though we, or an angel from heaven, preach any other gospel unto you than that which we have preached unto you, let him be accursed.`, citation: `Galatians 1:8` },
    ],
  },
  {
    numeral: 'XVII',
    title: `The Councils: Guarding the Faith Once Delivered`,
    blocks: [
      { type: 'p', text: `The pattern already shown in Movement XIII, apostles and elders gathered in council, judging a dispute over doctrine, issuing a decision in the name of the Holy Ghost, was never presented in Scripture as a one-time event, permitted only while the apostles themselves were alive. Christ had already promised something ongoing:` },
      { type: 'quote', text: `I have yet many things to say unto you, but ye cannot bear them now. Howbeit when he, the Spirit of truth, is come, he will guide you into all truth: for he shall not speak of himself; but whatsoever he shall hear, that shall he speak: and he will shew you things to come.`, citation: `John 16:12–13` },
      { type: 'p', text: `Guide, not guided once and left. Paul describes the purpose for which Christ gave the Church its ordained offices in the same ongoing terms, and names explicitly the doctrinal chaos such offices exist to prevent:` },
      { type: 'quote', text: `And he gave some, apostles; and some, prophets; and some, evangelists; and some, pastors and teachers; For the perfecting of the saints, for the work of the ministry, for the edifying of the body of Christ: Till we all come in the unity of the faith, and of the knowledge of the Son of God, unto a perfect man, unto the measure of the stature of the fulness of Christ: That we henceforth be no more children, tossed to and fro, and carried about with every wind of doctrine, by the sleight of men, and cunning craftiness, whereby they lie in wait to deceive.`, citation: `Ephesians 4:11–14` },
      { type: 'p', text: `Paul tells Timothy this deposit of teaching is not simply to be believed privately. It is to be guarded, kept, as a trust that does not expire with him:` },
      { type: 'quote', text: `O Timothy, keep that which is committed to thy trust, avoiding profane and vain babblings, and oppositions of science falsely so called.`, citation: `1 Timothy 6:20` },
      { type: 'quote', text: `Hold fast the form of sound words, which thou hast heard of me, in faith and love which is in Christ Jesus. That good thing which was committed unto thee keep by the Holy Ghost which dwelleth in us.`, citation: `2 Timothy 1:13–14` },
      { type: 'p', text: `This is exactly the pattern the Church continued to exercise in the centuries after the apostles died, using the same authority already established in Movement III, the same council model already established in Movement XIII, and the same charge to guard sound words just given to Timothy. When new teachers arose from among the Church’s own, exactly as Movement XVI already warned they would, disputing who Christ truly is or what He accomplished, the bishops did not each consult their own Bible in isolation and go their separate ways. They gathered, as the apostles and elders had gathered at Jerusalem, and judged the matter, and the faith once delivered to the saints was guarded rather than lost. This document has already shown you, from Scripture alone, the four marks such a council would need: one visible Church, apostles with real authority, elders ordained in unbroken succession from them, and the Spirit promised to guide that whole body into truth. Whatever you decide about any single council afterward, the pattern that made them possible, and necessary, is not later invention. It is already here, in the movements above.` },
    ],
  },
  {
    numeral: 'XVIII',
    title: `One Church, Two Claims to It`,
    blocks: [
      { type: 'p', text: `Everything to this point has been built from Scripture alone, quote joined to quote. What follows is different, and said so plainly: this part draws on the recorded history of the ancient Church, the acts of her councils, and the documented conduct of the bishops of Rome, not on further Bible verses, because the question it answers is a question history has to settle, not one more verse can settle alone.` },
      { type: 'p', text: `Part One has already shown, from Scripture, four marks of the Church Christ founded: one visible body, not many (Movement I); apostolic authority handed to real successors by ordination (Movements II and III); disputes settled by a council of the whole Church rather than by private judgment or by any single bishop’s decree (Movement XI’s account of Jerusalem, Movement XVII’s pattern of the councils that followed); and a faith guarded rather than added to, generation after generation (Movement VII, Movement XXIII below).` },
      { type: 'p', text: `For the first thousand years of Christian history, one communion held those marks together across five ancient sees: Rome, Constantinople, Alexandria, Antioch, and Jerusalem. Then a division opened between Rome and the other four, a division that has never closed. Both sides today claim to be that same, one, apostolic Church. Only one of them can be. This part asks which side actually kept the pattern Scripture already required, and does so from the historical record itself, since that record, not a new set of verses, is what actually answers the question.` },
    ],
  },
  {
    numeral: 'XIX',
    title: `Primacy of Honor, Not Universal Jurisdiction`,
    blocks: [
      { type: 'p', text: `From the earliest centuries, the Bishop of Rome held a real and unique honor among the sees, a primacy recognized by East and West alike. But a primacy of honor is not the same claim Rome makes of itself today: that the Pope holds direct, ordinary jurisdiction over every bishop, priest, and believer on earth, and, since 1870, that he can define doctrine without needing the consent of the other bishops or a council at all.` },
      { type: 'p', text: `The early Ecumenical Councils show which kind of primacy the whole Church actually recognized. The Second Ecumenical Council, meeting in Constantinople in 381, ruled that the Bishop of Constantinople should hold the rank of honor immediately after the Bishop of Rome, because Constantinople was “New Rome,” a ranking of honor between sees, not a statement of Roman jurisdiction over Constantinople. The Fourth Ecumenical Council, at Chalcedon in 451, went further still: its twenty-eighth canon granted Constantinople privileges equal to Rome’s, on the same grounds, that Constantinople now held the place Rome once held as the seat of empire. Rome’s own legates objected to that canon at the time and refused to sign it. That objection is itself telling. If universal Roman jurisdiction over the whole Church had already been the common faith of Christendom, there would have been no council, in the very act of ordering the Church’s own structure, treating Constantinople’s honor as comparable to Rome’s, and no need for Rome to object rather than simply invoke an authority everyone already granted it.` },
      { type: 'p', text: `This is not a small procedural dispute. It bears directly on Movement XVII’s pattern: bishops gathered in council, under Christ the one Head, correct error and define the faith together. A single bishop holding universal, ordinary jurisdiction over every other bishop, exercised even over the sustained objection of the other ancient patriarchs, is a different kind of authority than the council of apostles and elders at Jerusalem, or any council that followed it for the Church’s first thousand years.` },
    ],
  },
  {
    numeral: 'XX',
    title: `The Filioque: An Uninvited Word in the Creed`,
    blocks: [
      { type: 'p', text: `In 381, the Second Ecumenical Council completed the Nicene Creed with a single clause about the Holy Spirit: “who proceeds from the Father.” That clause locates the eternal source of the Trinity, its “monarchy,” in the Father alone, the same pattern the Creed already used for the Son, “begotten of the Father.” No Ecumenical Council ever amended that line.` },
      { type: 'p', text: `In the West, however, a local addition began to spread: “and the Son,” in Latin, *Filioque*, inserted after “who proceeds from the Father.” Its earliest known use was at a regional council in Toledo, Spain, in 589, meant to reinforce the full divinity of Christ against the last traces of Arianism among Spain’s recently converted Visigothic population. As a local, pastoral clarification, it drew little notice for centuries. By the early 800s, though, it had spread into Charlemagne’s Frankish territories, and Frankish bishops began pressing Rome to adopt it for the whole Western Church.` },
      { type: 'p', text: `Here is the detail most Western Christians are never told. Pope Leo III refused. When the Franks raised the question formally at the Council of Aachen in 809 and asked Rome to sanction the addition, Leo III would not permit it to be sung in the Creed at Mass, even though he was not necessarily hostile to the theological point the Franks were making about Christ’s divinity. His objection was about authority, not wording: no bishop, not even the Bishop of Rome, had the standing to alter a Creed an Ecumenical Council had defined for the whole Church. To make his refusal impossible to quietly reverse later, Leo III had the Creed, without the *Filioque*, inscribed in Greek and in Latin on two silver shields and displayed at St. Peter’s Basilica in Rome, specifically so no future pope could claim the unaltered text had simply been lost or forgotten.` },
      { type: 'p', text: `Rome held that line for two centuries. Only in 1014, at the coronation of the German Emperor Henry II, under pressure from the same Frankish-German imperial tradition that had asked Leo III and been refused, was the *Filioque* finally sung in Rome itself, under Pope Benedict VIII. A regional Spanish clarification, then a Frankish preference one Bishop of Rome had personally rejected as beyond any single see’s authority, became binding Roman doctrine only two hundred years after Leo III drew that line, and more than six hundred years after the Council whose text it altered.` },
      { type: 'p', text: `This matters for the whole argument of this document for a simple reason. The historical record shows Rome itself, in the person of one of its own bishops, once holding the position this document has called Orthodox: that no single see may alter what an Ecumenical Council defined for the whole Church. Later Rome did not preserve that position. It reversed it.` },
    ],
  },
  {
    numeral: 'XXI',
    title: `The Eighth Ecumenical Council`,
    blocks: [
      { type: 'p', text: `The clearest single episode in this history is also the least discussed in the West, and it is the center of this part.` },
      { type: 'p', text: `In 858, the Byzantine Patriarch Ignatios was deposed in a court dispute and replaced by Photius, a layman rapidly ordained through the clerical ranks to fill the vacant see. Rome, under Pope Nicholas I, initially objected to the irregularity of the appointment. In 869-870, a council convened in Constantinople, with attendance that started at only a dozen bishops and grew, across its sessions, to roughly a hundred, many signing under considerable imperial pressure. It condemned and deposed Photius and restored Ignatios. Centuries later, once Rome had settled into permanent separation from the East, this small 869-870 council was retroactively adopted into the West’s own count of Ecumenical Councils as the eighth.` },
      { type: 'p', text: `That was not the end of the story, even in the ninth century itself. Ignatios died in 877, Photius was restored to the patriarchate, and in 879-880 a much larger council assembled in Constantinople, traditionally numbered at several hundred bishops, by many accounts the best-attended council since Chalcedon itself. Papal legates from Rome were present and took part throughout. This council annulled the findings of the 869-870 synod, fully restored Photius, and, according to its own acts, bound the whole Church, East and West alike, never to alter the Creed defined at the Second Ecumenical Council, by addition or by subtraction, a prohibition aimed squarely at the *Filioque* already circulating in the Frankish West. Pope John VIII corresponded with Photius, recognized the reconciliation, and did not repudiate the council at the time.` },
      { type: 'p', text: `Here is the problem this poses for Rome’s own account of its history. If the smaller, later-adopted 869-870 council is truly the eighth Ecumenical Council, then the far larger 879-880 council, the one Rome’s own legates sat in, which explicitly overturned the earlier council’s findings and forbade altering the Creed, would have to be treated as illegitimate. But Rome’s own pope at the time did not treat it that way. Only generations later, after the permanent break of 1054 and after Rome’s own adoption of the *Filioque* in 1014, did the West quietly settle on 869-870 as its eighth Ecumenical Council, leaving 879-880, the council its own legates had attended and its own pope had accepted, out of its history altogether.` },
      { type: 'p', text: `The Orthodox Church holds, on this evidence, that if an eighth Ecumenical Council belongs in the line running from Nicaea through Chalcedon to the Second Council of Nicaea, the council that actually meets the pattern already shown in Movement XVII, apostles and elders gathered in the greatest numbers, judging a dispute, and guarding the Creed once delivered, is Constantinople in 879-880, not the smaller synod of 869-870 that Rome adopted only after the schism was final. Rome did not lose that council. It walked away from it, after the fact, once holding a different council to a different standard had become convenient.` },
    ],
  },
  {
    numeral: 'XXII',
    title: `Unilateral Dogma After the Schism`,
    blocks: [
      { type: 'p', text: `Once separated from the conciliar structure that had produced every one of the first seven Ecumenical Councils jointly with the other ancient sees, Rome did not stop defining doctrine. It changed how doctrine got defined. Three examples show the pattern plainly.` },
      { type: 'p', text: `In 1854, Pope Pius IX, by the bull *Ineffabilis Deus*, declared the Immaculate Conception of Mary, that she was conceived without the stain of original sin, to be dogma binding on every Catholic. No Ecumenical Council was called. The pope defined it alone, on his own authority.` },
      { type: 'p', text: `In 1870, the First Vatican Council defined papal infallibility itself: that the pope, speaking *ex cathedra* on faith or morals, teaches without the possibility of error and without needing the consent of the other bishops to do so. Notice the shape of this: a council was convened exactly once, to establish that councils would no longer be necessary afterward. Every one of the first seven Ecumenical Councils had involved the whole Church, all five ancient sees, arriving at a common mind together. Vatican I made that process permanently optional for Rome going forward.` },
      { type: 'p', text: `In 1950, Pope Pius XII, by the bull *Munificentissimus Deus*, defined the bodily Assumption of Mary into heaven as dogma, again without an Ecumenical Council, exercising the very authority Vatican I had defined eighty years earlier.` },
      { type: 'p', text: `Set this pattern beside Movement VII of this document: John himself chose to leave things unwritten, Paul reserved some instruction for his own presence, and yet what the apostles delivered, whether by word or by epistle, was received and guarded by the whole Church together, never issued as the private decree of one bishop over the absence or objection of the rest. The Orthodox Church has defined nothing by this method in nearly a thousand years, not because it stopped thinking, but because it never stopped believing that only the whole Church, gathered, can bind the whole Church.` },
    ],
  },
  {
    numeral: 'XXIII',
    title: `Further Divergences, Briefly`,
    blocks: [
      { type: 'p', text: `A shorter list follows, each item resting on the same underlying disagreement already described: whether teaching authority belongs to the whole body in council, or to Rome alone.` },
      { type: 'p', text: `*Original Sin and the Immaculate Conception.* The Latin Church, following Augustine, has generally taught that Adam’s sin is transmitted as inherited guilt, which is why Mary’s own conception had to be specially exempted by a further dogma. The Greek Fathers taught instead that what is inherited is mortality and corruption, not personal guilt for Adam’s act. The Orthodox Church honors Mary in the terms Movement XII already showed from Scripture, highly favored, blessed among women, without needing a doctrine its own theology of ancestral sin never required.` },
      { type: 'p', text: `*Purgatory and Indulgences.* Rome developed a defined doctrine of a place of temporal, purifying punishment after death, joined to a system of merit that could be earned, stored, and transferred between souls, the same system whose abuse in the sale of indulgences helped provoke the Protestant Reformation. The Orthodox Church prays for the dead, trusting God’s mercy, without teaching a defined purgatorial fire or a transferable treasury of merit.` },
      { type: 'p', text: `*Essence and Energies.* In the fourteenth century, St. Gregory Palamas defended, against the monk Barlaam of Calabria, the reality of the uncreated divine energies, God’s own activity and glory, by which a believer can truly experience and partake of God Himself, distinct from His essence, which remains forever beyond direct human knowledge. Rome’s theology, following Aquinas, generally treats grace as created, an effect of God’s action rather than a direct, uncreated participation in God’s own life. This shapes what Orthodox Christians mean by theosis, becoming, in Peter’s own words, “partakers of the divine nature” (2 Peter 1:4): a real participation, not merely a created likeness.` },
      { type: 'p', text: `*Leavened Bread.* Among the specific grievances traded in the mutual excommunications of 1054 itself was the question of unleavened bread, *azymes*, used in the Latin Eucharist, against the Greek insistence on leavened bread, understood to symbolize the living, risen Christ rather than the unleavened bread of Israel’s hurried exodus.` },
      { type: 'p', text: `*Clerical Marriage.* The apostolic canons and the Council in Trullo of 692, which Rome has never accepted as ecumenical, permitted married men to be ordained as priests and deacons, a practice the Orthodox Church has maintained ever since, while still reserving the episcopate to celibate or widowed clergy. Rome’s Latin rite has instead required celibacy of all priests, a discipline rather than a dogma, but one it has treated in practice as fixed.` },
      { type: 'p', text: `*The Development of Doctrine.* Since the nineteenth century, Roman Catholic theology has increasingly explained changes like these through a theory that dogma itself develops, that the Church can, under papal guidance, bring forth genuinely new content from what was before only implicit. Orthodox theology holds instead that the Church can clarify and defend the faith once delivered against a given error, as the Ecumenical Councils did against Arius, Nestorius, and the iconoclasts, but cannot add new content to that deposit, only guard it, exactly as Movements VII and XII of this document have already shown from Scripture itself.` },
    ],
  },
  {
    numeral: 'XXIV',
    title: `The Call to Return to the Old Paths`,
    blocks: [
      { type: 'p', text: `Long before the apostles, the same pattern of departure and the same remedy were already spoken by the prophet Jeremiah, in words that read as though written for exactly this moment:` },
      { type: 'quote', text: `Thus saith the LORD, Stand ye in the ways, and see, and ask for the old paths, where is the good way, and walk therein, and ye shall find rest for your souls. But they said, We will not walk therein.`, citation: `Jeremiah 6:16` },
      { type: 'p', text: `Not a new way discovered this generation. Not the newest, most persuasive interpretation, or the friendliest teacher. The *old* paths: the good way, already walked, already known, only needing to be asked for and found again.` },
      { type: 'p', text: `And so the case ends where it began, with Paul’s charge to hold what was handed down, and with the very words of Hebrews that first modeled this way of speaking: quote joined to quote, apostle joined to apostle, one voice:` },
      { type: 'quote', text: `Therefore, brethren, stand fast, and hold the traditions which ye have been taught, whether by word, or our epistle.`, citation: `2 Thessalonians 2:15` },
      { type: 'quote', text: `Remember them which have the rule over you, who have spoken unto you the word of God: whose faith follow.… Obey them that have the rule over you, and submit yourselves: for they watch for your souls, as they that must give account.`, citation: `Hebrews 13:7,17` },
      { type: 'p', text: `One Church. One faith. One baptism. One bread. One altar. One body, entered by water and the Spirit, fed by His own flesh and blood, with elders ordained by the laying on of hands, in a line running from the apostles to the men Paul calls “faithful,” to those *faithful men* teaching *others also*, not a chain broken and refounded in every generation according to each man’s private judgment, but the *old paths*, still there, still able to be asked for, still able to be walked.` },
    ],
  },
]
